---
title: "Vaccine Hesitancy and Society"
author: 
  - Benny Rochwerg
thanks: "All files associated with this analysis can be found here: <https://github.com/bennyrochwerg/vaccine-hesitancy-and-society/>"
date: "January 23, 2024"
date-format: long
format: pdf
bibliography: references.bib
---

Vaccine hesitancy refers to a practice whereby individuals avoid or defer vaccinations that are available to them [@phac]. This arises for several reasons, including the belief that vaccines do not work and worry over potential vaccine side effects [@phac]. However, vaccine hesitancy is not a harmless phenomenon; for instance, during the COVID-19 pandemic, vaccine hesitancy was found to have contributed to several thousand deaths [@globeandmail]. As a result, understanding the background of this issue is critical in order to protect society from its harmful impacts.

The origins of vaccine hesitancy date back hundreds of years [@criver]. For instance, there was religious opposition to the original smallpox vaccine following its creation in the late 18th century [@criver]. However, one major recent contributor to vaccine hesitancy is a research study by Andrew Wakefield from 1998 [@criver].

Wakefield's study concluded that there was a causal relationship between vaccination for measles, mumps, and rubella (MMR) and autism [@criver]. In this paper, a small sample size of 12 children consisting of all but one boy was employed [@wakefield]. This appears to limit the ability to which the findings of the research can be extrapolated to the overall human population.

In addition, the paper includes a description of the purported event that was associated with the beginning of each child's behavioural issues [@wakefield]. However, the paper indicates that these events, most of which are listed as "MMR", were either "identified by parents or doctor" [@wakefield]. This makes it impossible to determine the extent to which these events were self-reported by the children's parents, casting further doubt on the research. For example, the behavioural issues in question may have started prior to vaccination but coincidentally became noticeable following vaccination, possibly leading these parents to believe that the vaccine caused their children's problems. Also, Wakefield was found to have cherry-picked data and was receiving financial support from the children's parents' lawyers who they hired in their quest to take vaccine companies to court [@criver]. This seemingly renders the paper worthless.

In 2021, Oxford University professor Amia Srinivasan stated that "I think we should be suspicious when we find ourselves attracted to data—very, very thin and weak data—that seem to justify beliefs that have held great currency in lots of societies throughout history, in a way that is conducive to the oppression of large segments of the population" [@cowen]. This quote is especially relevant to the dataset used in the Wakefield paper [@wakefield]. Namely, the dataset was extremely minimal (for instance, there were only 12 participants), and the paper itself acknowledges that "We did not prove an association between measles, mumps, and rubella vaccine and the syndrome described" [@wakefield]. Despite this, Wakefield's results were followed by an observable decline in vaccination uptake in the United Kingdom [@criver], indicating that this small dataset had an outsized impact on the population. This led to thousands of measles cases and a number of deaths from the disease during a 20-year period of lower vaccination uptake in the United Kingdom [@criver], clearly contributing to the oppression of innocent individuals in society.

Moreover, @datafeminism point out that "numbers [...] cannot speak for themselves" and that "when those numbers derive from a data setting influenced by differentials of power, or by misaligned collection incentives (read: pretty much all data settings), and especially when the numbers have to do with human beings or their behavior, then they run the risk not only of being arrogantly grandiose and empirically wrong, but also of doing real harm in their reinforcement of an unjust status quo". This is especially true for the Wakefield paper. Namely, the data collection process for the paper by @wakefield was undertaken in order to support legal action against the companies who made the vaccine [@deer], not in pursuit of scientific understanding, ultimately resulting in misinformation that has harmed many individuals in our society [@criver].

Overall, vaccine hesitancy has contributed to societal harm. This has been bolstered by a dataset within a paper by @wakefield, which suggested the presence of a link between the MMR vaccine and autism. Ultimately, this underscores a need for greater scientific literacy among the general public as well as among media organizations to prevent this type of dangerous misinformation from taking hold in society in the future. Additional research should be performed to determine practices that would assist with the achievement of this objective.

\newpage

# References